### ISSUE TITLE
Cần phải có .gitignore

### ISSUE THREAD

**Issue by hieumdd** [vuanembi/assigment_1#3]
Python khi chạy sẽ xuất hiện nhiều file temp, mình cần nhét đống đó vào .gitignore để repo trông sạch.
Mình tìm extenstion `.gitignore` trên vscode, nó sẽ tự gen ra file cho mình cần

**Comment by huyen2510** [comment]
trừ nhánh không dùng pandas (fix_issue4) em merge các nhánh (tương ứng mỗi issue) còn lại vào main rồi ạ

**Comment by hieumdd** [comment]
một số file do bị commit trc khi nó dc thêm vào .gitignore, nên nó vẫn đang bị lưu trong đó `__pycache__`
mình cần phải remove nó khỏi git version control. tìm `git rm` để có cách xoá
